version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: innoserve_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./nodejs_app/model/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rag_network
    restart: unless-stopped

  app:
    container_name: nodejs_backend
    build: ./nodejs_app
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs_app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app_db
      DB_PORT: 3306
      RAG_SERVICE_URL: http://rag_api:5001/generate
      JWT_SECRET: your-very-long-and-secure-secret-key
    depends_on:
      - mariadb
      - rag_api
    networks:
      - rag_network
    restart: unless-stopped

  rag_api:
    container_name: python_rag_api
    build: ./python_rag_service
    ports:
      - "5001:5001"
    volumes:
      - ./python_rag_service:/usr/src/app
      - chroma_data:/data
    environment:
      JWT_ALGORITHM: HS256
      JWT_SECRET: your-very-long-and-secure-secret-key
      GOOGLE_CSE_ID: 227946b3c2ab745ab
      GOOGLE_SEARCH_API_KEY: AIzaSyDCDG7AtOU2h7DaEZgMdvj2YQEQnd3OvXM
      GEMINI_API_KEY: AIzaSyBbjo21Qs46X0-VqxAh2zTxMAkQNaGHBgY
    networks:
      - rag_network
    restart: unless-stopped

networks:
  rag_network:
    driver: bridge

volumes:
  mariadb_data:
  chroma_data: