# 使用官方的 Python 3.10 slim 作為基礎映像檔
FROM python:3.10-slim

# 設定工作目錄
WORKDIR /usr/src/app

# 複製依賴需求檔案
COPY requirements.txt ./

# 安裝 Python 依賴
# --no-cache-dir 選項可以減少映像檔體積
RUN pip install --no-cache-dir -r requirements.txt

# 複製所有剩餘的專案檔案
COPY . .

# 宣告容器將在 5001 port 上監聽
EXPOSE 5001

# 啟動 Flask 應用程式的進入點改為 run.py
CMD [ "python", "-u", "run.py" ]

